<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-VV0I5IH" name="com.abstech.airface.CompensatoryPage" tests="8" failures="0" timestamp="2020-08-13T15:38:14 IST" time="113.483" errors="1">
  <testcase name="setting_Compensatory_module" time="4.652" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
  <testcase name="Compensatory_message_validation" time="0.087" classname="com.abstech.airface.CompensatoryPage">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.abstech.airface.CompensatoryPage.Compensatory_message_validation(CompensatoryPage.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Compensatory_message_validation -->
  <system-out/>
  <testcase name="Compensatory_duplicate_message_validation" time="17.653" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
  <testcase name="Compensatory_dup_message_validation" time="0.072" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
  <testcase name="Setting_Compensatory_Search" time="0.168" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
  <testcase name="Setting_compensatory_edit" time="26.928" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
  <testcase name="download" time="9.448" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
  <testcase name="Setting_compensatory_delete" time="54.475" classname="com.abstech.airface.CompensatoryPage"/>
  <system-out/>
</testsuite> <!-- com.abstech.airface.CompensatoryPage -->
